/**
 * Task 56: Playwright E2E tests for Sutter import error scenarios.
 *
 * Tests error handling for:
 * - File with no valid tabs
 * - Missing physician selection
 * - Empty physician tab
 *
 * Prerequisites:
 * - Backend and frontend servers running (localhost:3000 and localhost:5173)
 * - Seeded database with at least one physician user
 * - Fixture Excel files in e2e/fixtures/ (generated by sutter-fixture-helper.ts)
 */

import { test, expect } from '@playwright/test';
import { ImportPage } from './pages/import-page';
import {
  getMultiTabFixturePath,
  getNoValidTabsFixturePath,
  getEmptyTabFixturePath,
} from './fixtures/sutter-fixture-helper';

// Admin credentials (from seed data)
const ADMIN_EMAIL = 'ko037291@gmail.com';
const ADMIN_PASSWORD = 'welcome100';

test.describe('Sutter Import - Error Scenarios', () => {
  let importPage: ImportPage;

  test.beforeEach(async ({ page }) => {
    importPage = new ImportPage(page);
    await importPage.goto(ADMIN_EMAIL, ADMIN_PASSWORD);
  });

  test('file with no valid tabs shows sheet discovery error', async ({ page }) => {
    const fixturePath = await getNoValidTabsFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);

    // Wait for sheet discovery to attempt and fail
    await importPage.waitForSheetDiscovery();

    // Should show an error about no valid tabs
    // The SheetSelector shows a "Sheet Discovery Failed" error block
    const errorText = await importPage.getSheetErrorText();
    // The error may come from either the SheetSelector error state or
    // the parent sheetError state
    const anyErrorVisible = errorText.length > 0 ||
      await page.locator('text=/[Nn]o.*physician.*tab|[Nn]o valid tab/').isVisible().catch(() => false);
    expect(anyErrorVisible).toBe(true);
  });

  test('missing physician selection prevents preview submission', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Select a tab but do NOT select a physician
    await importPage.selectSheet('Smith, John');
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // If auto-match selected a physician, clear it
    const currentValue = await importPage.getSelectedPhysician();
    if (currentValue) {
      // Set to the empty placeholder option
      await importPage.physicianDropdown.selectOption('');
    }

    // "Please select a physician" warning should be visible
    const warningVisible = await importPage.isPhysicianWarningVisible();
    expect(warningVisible).toBe(true);

    // Try clicking Preview Import
    await importPage.clickPreview();

    // Should show an error about missing physician
    // Wait a moment for error to display
    await page.waitForTimeout(500);

    const errorText = await importPage.getErrorText();
    expect(errorText).toContain('physician');
  });

  test('missing tab selection prevents preview submission', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Do NOT select a tab (leave on placeholder)
    // The physician dropdown won't appear until tab is selected

    // Try clicking Preview Import
    await importPage.clickPreview();

    // Should show an error about missing tab
    await page.waitForTimeout(500);

    const errorText = await importPage.getErrorText();
    expect(errorText).toContain('tab');
  });

  test('empty physician tab shows error on preview', async ({ page }) => {
    const fixturePath = await getEmptyTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // The single tab should be auto-selected (only one valid tab)
    const selectedSheet = await importPage.getSelectedSheet();
    // Should be "Empty, Doctor" or auto-selected
    if (!selectedSheet) {
      await importPage.selectSheet('Empty, Doctor');
    }

    // Wait for physician dropdown
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // Select a physician
    const options = await importPage.physicianDropdown.locator('option').all();
    for (const option of options) {
      const value = await option.getAttribute('value');
      if (value && value !== '') {
        await importPage.physicianDropdown.selectOption(value);
        break;
      }
    }

    // Click Preview Import
    await importPage.clickPreview();

    // Should show an error about empty tab or no data
    // Wait for the API call to return and error to display
    await page.waitForTimeout(3000);

    // The error could appear as a page-level error or the preview could
    // navigate and show an error there
    const currentUrl = page.url();
    if (currentUrl.includes('/preview/')) {
      // If navigated to preview, it should show an error state
      const errorVisible = await page.locator('.bg-red-50').isVisible().catch(() => false);
      expect(errorVisible).toBe(true);
    } else {
      // If stayed on import page, error should be shown inline
      const errorText = await importPage.getErrorText();
      expect(errorText.length).toBeGreaterThan(0);
    }
  });

  test('Preview Import button stays disabled without file upload', async ({ page }) => {
    await importPage.selectSystem('sutter');

    // Without uploading a file, the button should be disabled
    expect(await importPage.isPreviewDisabled()).toBe(true);
  });
});
