/**
 * Task 57: Playwright E2E tests for Sutter import edge cases.
 *
 * Tests edge cases including:
 * - Single-tab file pre-selects tab automatically
 * - Manual physician override after auto-match
 * - Switching from Sutter to Hill system clears sheet state
 *
 * Prerequisites:
 * - Backend and frontend servers running (localhost:3000 and localhost:5173)
 * - Seeded database with at least one physician user
 * - Fixture Excel files in e2e/fixtures/ (generated by sutter-fixture-helper.ts)
 */

import { test, expect } from '@playwright/test';
import { ImportPage } from './pages/import-page';
import {
  getMultiTabFixturePath,
  getSingleTabFixturePath,
} from './fixtures/sutter-fixture-helper';

// Admin credentials (from seed data)
const ADMIN_EMAIL = 'ko037291@gmail.com';
const ADMIN_PASSWORD = 'welcome100';

test.describe('Sutter Import - Edge Cases', () => {
  let importPage: ImportPage;

  test.beforeEach(async ({ page }) => {
    importPage = new ImportPage(page);
    await importPage.goto(ADMIN_EMAIL, ADMIN_PASSWORD);
  });

  test('single-tab file pre-selects the tab automatically', async ({ page }) => {
    const fixturePath = await getSingleTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // With only one valid tab, it should be auto-selected
    const selectedSheet = await importPage.getSelectedSheet();
    expect(selectedSheet).toBe('Williams, Pat');

    // Tab count should show 1
    const tabCountText = await importPage.getTabCountText();
    expect(tabCountText).toContain('1 valid tab');
  });

  test('manual physician override replaces auto-matched suggestion', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Select a tab to trigger auto-match
    await importPage.selectSheet('Smith, John');
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // Record the auto-matched physician (if any)
    const autoMatchedValue = await importPage.getSelectedPhysician();

    // Get all physician options (excluding placeholder)
    const options = await importPage.physicianDropdown.locator('option').all();
    const availablePhysicians: { value: string; text: string }[] = [];
    for (const option of options) {
      const value = await option.getAttribute('value');
      const text = await option.innerText();
      if (value && value !== '') {
        availablePhysicians.push({ value, text });
      }
    }

    // If there are at least 2 physicians, select a different one to test override
    if (availablePhysicians.length >= 2) {
      const differentPhysician = availablePhysicians.find(
        (p) => p.value !== autoMatchedValue
      );
      if (differentPhysician) {
        await importPage.physicianDropdown.selectOption(differentPhysician.value);

        // Verify the selection changed
        const newValue = await importPage.getSelectedPhysician();
        expect(newValue).toBe(differentPhysician.value);

        // The "Auto-matched" text should no longer be visible (since we manually changed it)
        // Note: the auto-match text shows only when selectedPhysicianId === suggestedPhysicianId
        if (autoMatchedValue && autoMatchedValue !== differentPhysician.value) {
          const autoMatchText = await importPage.getAutoMatchText();
          expect(autoMatchText).toBe('');
        }
      }
    }

    // Regardless, the physician dropdown should be functional
    expect(await importPage.physicianDropdown.isVisible()).toBe(true);
  });

  test('switching from Sutter to Hill system resets sheet selection state', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    // Start with Sutter
    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Verify sheet selector is visible
    expect(await importPage.isSheetSelectorStepVisible()).toBe(true);

    // Select a tab
    await importPage.selectSheet('Smith, John');
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // Now switch to Hill system — sheet state resets
    await importPage.selectSystem('hill');

    // The Step 4 section remains visible (file is still uploaded),
    // but the SheetSelector re-triggers discovery for the Hill system.
    // Wait for sheet discovery to complete for the new system
    await importPage.waitForSheetDiscovery();

    // The Preview Import button should be disabled (sheet/physician state was reset)
    expect(await importPage.isPreviewDisabled()).toBe(true);
  });

  test('switching from Hill to Sutter and re-uploading discovers correct tabs', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    // Start with Hill (default)
    // Switch to Sutter, then upload a Sutter file
    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Sheet selector should be visible with Sutter physician tabs
    expect(await importPage.isSheetSelectorStepVisible()).toBe(true);

    const sheetOptions = await importPage.getSheetOptions();
    expect(sheetOptions).toContain('Smith, John');
    expect(sheetOptions).toContain('Jones, Mary');
  });

  test('removing file and re-uploading resets sheet selection', async ({ page }) => {
    const multiTabPath = await getMultiTabFixturePath();
    const singleTabPath = await getSingleTabFixturePath();

    await importPage.selectSystem('sutter');

    // Upload multi-tab file
    await importPage.uploadFile(multiTabPath);
    await importPage.waitForSheetDiscovery();

    // Select a tab
    await importPage.selectSheet('Smith, John');
    const sheetOptions1 = await importPage.getSheetOptions();
    expect(sheetOptions1).toContain('Smith, John');
    expect(sheetOptions1).toContain('Jones, Mary');

    // Remove the file
    await importPage.removeFile();

    // Sheet selector should disappear (no file)
    expect(await importPage.isSheetSelectorStepVisible()).toBe(false);

    // Upload a different file (single-tab)
    await importPage.uploadFile(singleTabPath);
    await importPage.waitForSheetDiscovery();

    // Sheet options should reflect the new file
    const sheetOptions2 = await importPage.getSheetOptions();
    expect(sheetOptions2).toContain('Williams, Pat');
    expect(sheetOptions2).not.toContain('Smith, John');

    // Single tab should be auto-selected
    const selectedSheet = await importPage.getSelectedSheet();
    expect(selectedSheet).toBe('Williams, Pat');
  });
});
