/**
 * Task 55: Playwright E2E tests for full Sutter import flow.
 *
 * Tests the complete user journey:
 *   select Sutter system -> upload file -> select tab -> confirm physician ->
 *   preview -> (optionally) execute
 *
 * Prerequisites:
 * - Backend and frontend servers running (localhost:3000 and localhost:5173)
 * - Seeded database with at least one physician user
 * - Fixture Excel files in e2e/fixtures/ (generated by sutter-fixture-helper.ts)
 */

import { test, expect } from '@playwright/test';
import { ImportPage, PreviewPage } from './pages/import-page';
import {
  getMultiTabFixturePath,
} from './fixtures/sutter-fixture-helper';

// Admin credentials (from seed data)
const ADMIN_EMAIL = 'ko037291@gmail.com';
const ADMIN_PASSWORD = 'welcome100';

test.describe('Sutter Import - Full Flow', () => {
  test.describe.configure({ mode: 'serial' });

  let importPage: ImportPage;

  test.beforeEach(async ({ page }) => {
    importPage = new ImportPage(page);
    await importPage.goto(ADMIN_EMAIL, ADMIN_PASSWORD);
  });

  test('selecting Sutter system shows Sutter/SIP in dropdown', async ({ page }) => {
    // The system dropdown should have both Hill and Sutter options
    const options = await importPage.systemDropdown.locator('option').allInnerTexts();
    expect(options).toContain('Hill Healthcare');
    expect(options).toContain('Sutter/SIP');
  });

  test('selecting Sutter and uploading file shows sheet selector step', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);

    // Wait for sheet discovery to complete
    await importPage.waitForSheetDiscovery();

    // The "Select Tab & Physician" step should be visible
    const isVisible = await importPage.isSheetSelectorStepVisible();
    expect(isVisible).toBe(true);
  });

  test('sheet discovery shows correct tab names (skip tabs filtered)', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Should show physician tabs, not skip tabs
    const sheetOptions = await importPage.getSheetOptions();
    expect(sheetOptions).toContain('Smith, John');
    expect(sheetOptions).toContain('Jones, Mary');

    // Skip tabs should NOT appear
    expect(sheetOptions).not.toContain('CAR Report');
    expect(sheetOptions).not.toContain('Perf by Measure Summary');
  });

  test('tab count text shows correct number of physician tabs', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    const tabCountText = await importPage.getTabCountText();
    expect(tabCountText).toContain('2 valid tabs');
  });

  test('physician auto-matching pre-selects correct physician on tab selection', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Select the "Smith, John" tab
    await importPage.selectSheet('Smith, John');

    // Wait for physician dropdown to appear
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // The physician dropdown should have an option with "(suggested)"
    const hasSuggested = await importPage.hasSuggestedLabel();
    // This may or may not have a match depending on seeded physician names
    // But the dropdown should be visible and populated
    const physicianOptions = await importPage.physicianDropdown.locator('option').allInnerTexts();
    expect(physicianOptions.length).toBeGreaterThan(1); // at least placeholder + 1 physician

    // If a physician with "Smith" exists in the seed data, verify auto-match
    const suggestedOption = physicianOptions.find((o) => o.includes('(suggested)'));
    if (suggestedOption) {
      // Auto-match text should be visible
      const autoMatchText = await importPage.getAutoMatchText();
      expect(autoMatchText).toContain('Auto-matched from tab name');
    }
  });

  test('selecting tab and physician enables Preview Import button', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Before selection, button should be disabled
    expect(await importPage.isPreviewDisabled()).toBe(true);

    // Select tab
    await importPage.selectSheet('Smith, John');
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // If auto-matched, button might already be enabled
    // If not, select a physician manually
    const selectedPhysician = await importPage.getSelectedPhysician();
    if (!selectedPhysician) {
      // Select the first non-placeholder option
      const options = await importPage.physicianDropdown.locator('option').all();
      for (const option of options) {
        const value = await option.getAttribute('value');
        if (value && value !== '') {
          await importPage.physicianDropdown.selectOption(value);
          break;
        }
      }
    }

    // Now the button should be enabled
    expect(await importPage.isPreviewDisabled()).toBe(false);
  });

  test('clicking Preview Import navigates to preview page', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Select tab
    await importPage.selectSheet('Smith, John');
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // Select physician (first available)
    const options = await importPage.physicianDropdown.locator('option').all();
    for (const option of options) {
      const value = await option.getAttribute('value');
      if (value && value !== '') {
        await importPage.physicianDropdown.selectOption(value);
        break;
      }
    }

    // Click Preview Import
    await importPage.clickPreview();

    // Should navigate to preview page
    await page.waitForURL(/\/patient-management\/preview\//, { timeout: 15000 });

    // Preview page should load
    const previewPage = new PreviewPage(page);
    await previewPage.waitForLoad();

    // Verify the header shows "Import Preview"
    await expect(previewPage.heading).toBeVisible();
  });

  test('preview page shows data from selected Sutter tab', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    await importPage.selectSheet('Smith, John');
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // Select physician
    const options = await importPage.physicianDropdown.locator('option').all();
    for (const option of options) {
      const value = await option.getAttribute('value');
      if (value && value !== '') {
        await importPage.physicianDropdown.selectOption(value);
        break;
      }
    }

    await importPage.clickPreview();
    await page.waitForURL(/\/patient-management\/preview\//, { timeout: 15000 });

    const previewPage = new PreviewPage(page);
    await previewPage.waitForLoad();

    // Preview should contain patient data from the "Smith, John" tab
    // The preview table should show 5 INSERT records for 2 patients
    await expect(page.getByText('New Patients:2')).toBeVisible({ timeout: 10000 });
    await expect(page.getByText('Doe, Jane').first()).toBeVisible({ timeout: 5000 });
    await expect(page.getByText('Brown, Bob').first()).toBeVisible({ timeout: 5000 });

    // File name should be displayed in header metadata
    await expect(page.getByText('sutter-multi-tab.xlsx')).toBeVisible();
  });

  test('preview page shows file metadata and record counts', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    await importPage.selectSheet('Smith, John');
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // Select physician
    const options = await importPage.physicianDropdown.locator('option').all();
    for (const option of options) {
      const value = await option.getAttribute('value');
      if (value && value !== '') {
        await importPage.physicianDropdown.selectOption(value);
        break;
      }
    }

    await importPage.clickPreview();
    await page.waitForURL(/\/patient-management\/preview\//, { timeout: 15000 });

    const previewPage = new PreviewPage(page);
    await previewPage.waitForLoad();

    // Mode metadata should be visible
    await expect(page.locator('text=Mode: merge')).toBeVisible();

    // Should show record count ("5 records will be modified" for 5 data rows)
    const modifyingText = await previewPage.getModifyingCountText();
    expect(modifyingText).toContain('records will be modified');
  });

  test('Jones tab with mixed actions only imports mapped rows', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // Select "Jones, Mary" tab which has 2 mapped and 2 unmapped actions
    await importPage.selectSheet('Jones, Mary');
    await importPage.physicianDropdown.waitFor({ state: 'visible', timeout: 5000 });

    // Select physician
    const options = await importPage.physicianDropdown.locator('option').all();
    for (const option of options) {
      const value = await option.getAttribute('value');
      if (value && value !== '') {
        await importPage.physicianDropdown.selectOption(value);
        break;
      }
    }

    await importPage.clickPreview();
    await page.waitForURL(/\/patient-management\/preview\//, { timeout: 15000 });

    const previewPage = new PreviewPage(page);
    await previewPage.waitForLoad();

    // Should only show 2 records (the mapped ones: Mammogram + Vaccine: Flu)
    await expect(page.getByText('2 records will be modified')).toBeVisible({ timeout: 5000 });
    await expect(page.getByText('Wilson, Sam').first()).toBeVisible();
    await expect(page.getByText('Garcia, Ana').first()).toBeVisible();
  });

  test('step numbering adjusts for Sutter (extra sheet selector step)', async ({ page }) => {
    const fixturePath = await getMultiTabFixturePath();

    await importPage.selectSystem('sutter');
    await importPage.uploadFile(fixturePath);
    await importPage.waitForSheetDiscovery();

    // For Sutter as ADMIN: steps should be
    // 1: Healthcare System
    // 2: Import Mode
    // 3: Upload File (no separate physician step for Sutter)
    // 4: Select Tab & Physician
    const systemStep = await importPage.getStepNumber('Select Healthcare System');
    expect(systemStep).toBe('1');

    const modeStep = await importPage.getStepNumber('Choose Import Mode');
    expect(modeStep).toBe('2');

    const uploadStep = await importPage.getStepNumber('Upload File');
    expect(uploadStep).toBe('3');

    const sheetStep = await importPage.getStepNumber('Select Tab & Physician');
    expect(sheetStep).toBe('4');
  });
});
